name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following to help us reproduce and fix the issue.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short summary of the issue.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug?
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, .NET version, etc.
    validations:
      required: false